name: Pull Request Build

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core CLI
      uses: actions/setup-dotnet@v1.1.0

    - name: Build
      run: |
        $VERSION = Get-Content 'src\version' -TotalCount 1
        $PACKAGE_VERSION = "$VERSION-build.${{ github.run_number }}"
        Write-Output "Generating Package with version: $PACKAGE_VERSION ..."
        $DESCRIPTION = Get-Content 'README.MD'
        $DESCRIPTION = $DESCRIPTION -join '\n\r'
        dotnet build src/GitHub.sln -p:Configuration=Release -o dist -p:Version=$VERSION -p:PackageVersion=$PACKAGE_VERSION -p:Description="$DESCRIPTION"
        dotnet pack  src/GitHub.sln -p:Configuration=Release -o dist -p:Version=$VERSION -p:PackageVersion=$PACKAGE_VERSION -p:Description="$DESCRIPTION"

    - name: Upload artifact
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: dist/*.nupkg
