name: Release Tagging

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Build
      run: |
        $Tag = "${{ github.ref }}" -replace '(refs/tags/)(.+)', '$2'
        $Version = $Tag -replace '((\d+)(\.\d+){1,3})(-.+|)', '$1'
        $InformationalVersion = "$Tag SHA-${{ github.SHA }}"
        $ProductVersion = "$InformationalVersion"
        $PackageVersion = $Tag
        dotnet pack  src\GitHub.sln -p:Configuration=Release -p:Version=$Version -p:PackageVersion=$PackageVersion -o dist
        dotnet nuget push dist\*.nupkg -k ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json
